version: '3'
services:
  mdw:
    hostname: mdw
    image: "gpdb6"
    ports:
     - "6222:22"
     - "6432:5432"
    volumes:
     - /data/mdw:/home/gpadmin/data
  sdw1:
    hostname: sdw0
    image: "gpdb6"
    volumes:
     - /data/sdw0:/home/gpadmin/data
  sdw2:
    hostname: sdw1
    image: "gpdb6"
    volumes:
     - /data/sdw1:/home/gpadmin/data
  sdw3:
    hostname: sdw2
    image: "gpdb6"
    volumes:
     - /data/sdw2:/home/gpadmin/data
  sdw4:
    hostname: sdw3
    image: "gpdb6"
    volumes:
     - /data/sdw3:/home/gpadmin/data
  etl:
    hostname: etl
    image: "gpdb6"
